---
name: "pre-release"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4.0.0"
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - id: "yarn-cache"
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: "actions/cache@v3.3.2"
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: "yarn install --immutable"
      - run: "yarn lintfix"
      - run: "yarn lint"
      - run: "yarn build"

      - uses: "./packages/automatic-releases/"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            packages/automatic-releases/dist/index.js
        id: "automatic_releases"

      - name: "Automatically mirror release artifacts"
        env:
          GITHUB_SUPER_TOKEN: ${{ secrets.SUPER_TOKEN }}
        run: |
          ./scripts/mirror-actions.sh "$AUTOMATIC_RELEASES_TAG"
