---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4.0.0"
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - id: "yarn-cache"
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: "actions/cache@v3.3.2"
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: "yarn install"
      - run: "yarn lintfix"
      - run: "yarn lint"
      - run: "yarn build"

      - uses: "crowbarmaster/GH-Automatic-Releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            packages/automatic-releases/dist/index.js
        id: "automatic_releases"

      # marvinpinto/action-automatic-releases
      - name: "Automatically mirror release artifacts"
        env:
          GITHUB_SUPER_TOKEN: ${{ secrets.SUPER_TOKEN }}
        run: |
          ./scripts/mirror-actions.sh "$AUTOMATIC_RELEASES_TAG"
